/* AUTOGENERATED. DO NOT EDIT. */
#include "_pcode.h"
void pcode2c(CPUState *state, size_t breakpoint)
{
    uint8_t *register_space = state->reg;
    uint8_t *unique_space = state->unique;
    uint8_t *ram_space = state->ram;
    uint8_t *ram = ram_space; // TODO: remove this
    for (;;)
    {
        switch (state->pc)
        {
        case 0x1011ce:
        L_0x1011ceul:
            INSN(0x1011ceul, "0x1011ce: ENDBR64 ")
        case 0x1011d2:
        L_0x1011d2ul:
            INSN(0x1011d2ul, "0x1011d2: PUSH RBP")
        L_P_0x1:
            COPY(unique_space + 0xed00ul, 8ul, register_space + 0x28ul /* RBP */, 8ul);
        L_P_0x2:
            INT_SUB(register_space + 0x20ul /* RSP */, 8ul, register_space + 0x20ul /* RSP */, 8ul, (uint8_t *)&(long unsigned int){0x8ul}, 0x8ul);
        L_P_0x3:
            STORE((uint8_t *)&(long unsigned int){0x56490307c750ul}, 0x8ul, register_space + 0x20ul /* RSP */, 8ul, unique_space + 0xed00ul, 8ul);
        case 0x1011d3:
        L_0x1011d3ul:
            INSN(0x1011d3ul, "0x1011d3: MOV RBP,RSP")
        L_P_0x4:
            COPY(register_space + 0x28ul /* RBP */, 8ul, register_space + 0x20ul /* RSP */, 8ul);
        case 0x1011d6:
        L_0x1011d6ul:
            INSN(0x1011d6ul, "0x1011d6: MOV dword ptr [RBP + -0x4],EDI")
        L_P_0x5:
            INT_ADD(unique_space + 0x3100ul, 8ul, register_space + 0x28ul /* RBP */, 8ul, (uint8_t *)&(long unsigned int){0xfffffffffffffffcul}, 0x8ul);
        L_P_0x6:
            COPY(unique_space + 0xbf00ul, 4ul, register_space + 0x38ul /* EDI */, 4ul);
        L_P_0x7:
            STORE((uint8_t *)&(long unsigned int){0x56490307c750ul}, 0x8ul, unique_space + 0x3100ul, 8ul, unique_space + 0xbf00ul, 4ul);
        case 0x1011d9:
        L_0x1011d9ul:
            INSN(0x1011d9ul, "0x1011d9: MOV EAX,0x1")
        L_P_0x8:
            COPY(register_space + 0x0ul /* RAX */, 8ul, (uint8_t *)&(long unsigned int){0x1ul}, 0x8ul);
        case 0x1011de:
        L_0x1011deul:
            INSN(0x1011deul, "0x1011de: POP RBP")
        L_P_0x9:
            LOAD(register_space + 0x28ul /* RBP */, 8ul, (uint8_t *)&(long unsigned int){0x56490307c750ul}, 0x8ul, register_space + 0x20ul /* RSP */, 8ul);
        L_P_0xa:
            INT_ADD(register_space + 0x20ul /* RSP */, 8ul, register_space + 0x20ul /* RSP */, 8ul, (uint8_t *)&(long unsigned int){0x8ul}, 0x8ul);
        case 0x1011df:
        L_0x1011dful:
            INSN(0x1011dful, "0x1011df: RET ")
        L_P_0xb:
            LOAD(register_space + 0x288ul /* RIP */, 8ul, (uint8_t *)&(long unsigned int){0x56490307c750ul}, 0x8ul, register_space + 0x20ul /* RSP */, 8ul);
        L_P_0xc:
            INT_ADD(register_space + 0x20ul /* RSP */, 8ul, register_space + 0x20ul /* RSP */, 8ul, (uint8_t *)&(long unsigned int){0x8ul}, 0x8ul);
        L_P_0xd:
            RETURN(register_space + 0x288ul /* RIP */, 8ul);
        default:
            assert(state->pc != -1); // Unexpected PC value
        }
    }
}