/* AUTOGENERATED. DO NOT EDIT. */
#include "_pcode.h"
void pcode2c(CPUState *state, size_t breakpoint) {
  uint8_t *register_space = state->reg;
  uint8_t *unique_space = state->unique;
  uint8_t *ram_space = state->ram;
  uint8_t *ram = ram_space; // TODO: remove this
  for (;;) {
    switch (state->pc) {
    case 0x1169:
    L_0x1169ul:
      INSN(0x1169ul, "0x1169: ENDBR64 ")
    case 0x116d:
    L_0x116dul:
      INSN(0x116dul, "0x116d: MOV EAX,0x0")
    L_P_0x1:
      COPY(register_space + 0x0ul /* RAX */, 8ul,
           (uint8_t *)&(long unsigned int){0x0ul}, 0x8ul);
    case 0x1172:
    L_0x1172ul:
      INSN(0x1172ul, "0x1172: JMP 0x1177")
    L_P_0x2:
      BRANCH_GOTO_TEMPFIX(ram_space, 0x1177ul, 8ul);
    case 0x1174:
    L_0x1174ul:
      INSN(0x1174ul, "0x1174: ADD EAX,0x1")
    L_P_0x3:
      INT_CARRY(register_space + 0x200ul /* CF */, 1ul,
                register_space + 0x0ul /* EAX */, 4ul,
                (uint8_t *)&(long unsigned int){0x1ul}, 0x4ul);
    L_P_0x4:
      INT_SCARRY(register_space + 0x20bul /* OF */, 1ul,
                 register_space + 0x0ul /* EAX */, 4ul,
                 (uint8_t *)&(long unsigned int){0x1ul}, 0x4ul);
    L_P_0x5:
      INT_ADD(register_space + 0x0ul /* EAX */, 4ul,
              register_space + 0x0ul /* EAX */, 4ul,
              (uint8_t *)&(long unsigned int){0x1ul}, 0x4ul);
    L_P_0x6:
      INT_ZEXT(register_space + 0x0ul /* RAX */, 8ul,
               register_space + 0x0ul /* EAX */, 4ul);
    L_P_0x7:
      INT_SLESS(register_space + 0x207ul /* SF */, 1ul,
                register_space + 0x0ul /* EAX */, 4ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x4ul);
    L_P_0x8:
      INT_EQUAL(register_space + 0x206ul /* ZF */, 1ul,
                register_space + 0x0ul /* EAX */, 4ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x4ul);
    L_P_0x9:
      INT_AND(unique_space + 0x13180ul, 4ul, register_space + 0x0ul /* EAX */,
              4ul, (uint8_t *)&(long unsigned int){0xfful}, 0x4ul);
    L_P_0xa:
      POPCOUNT(unique_space + 0x13200ul, 1ul, unique_space + 0x13180ul, 4ul);
    L_P_0xb:
      INT_AND(unique_space + 0x13280ul, 1ul, unique_space + 0x13200ul, 1ul,
              (uint8_t *)&(long unsigned int){0x1ul}, 0x1ul);
    L_P_0xc:
      INT_EQUAL(register_space + 0x202ul /* PF */, 1ul,
                unique_space + 0x13280ul, 1ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x1ul);
    case 0x1177:
    L_0x1177ul:
      INSN(0x1177ul, "0x1177: CMP EAX,EDI")
    L_P_0xd:
      INT_LESS(register_space + 0x200ul /* CF */, 1ul,
               register_space + 0x0ul /* EAX */, 4ul,
               register_space + 0x38ul /* EDI */, 4ul);
    L_P_0xe:
      INT_SBORROW(register_space + 0x20bul /* OF */, 1ul,
                  register_space + 0x0ul /* EAX */, 4ul,
                  register_space + 0x38ul /* EDI */, 4ul);
    L_P_0xf:
      INT_SUB(unique_space + 0x29700ul, 4ul, register_space + 0x0ul /* EAX */,
              4ul, register_space + 0x38ul /* EDI */, 4ul);
    L_P_0x10:
      INT_SLESS(register_space + 0x207ul /* SF */, 1ul,
                unique_space + 0x29700ul, 4ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x4ul);
    L_P_0x11:
      INT_EQUAL(register_space + 0x206ul /* ZF */, 1ul,
                unique_space + 0x29700ul, 4ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x4ul);
    L_P_0x12:
      INT_AND(unique_space + 0x13180ul, 4ul, unique_space + 0x29700ul, 4ul,
              (uint8_t *)&(long unsigned int){0xfful}, 0x4ul);
    L_P_0x13:
      POPCOUNT(unique_space + 0x13200ul, 1ul, unique_space + 0x13180ul, 4ul);
    L_P_0x14:
      INT_AND(unique_space + 0x13280ul, 1ul, unique_space + 0x13200ul, 1ul,
              (uint8_t *)&(long unsigned int){0x1ul}, 0x1ul);
    L_P_0x15:
      INT_EQUAL(register_space + 0x202ul /* PF */, 1ul,
                unique_space + 0x13280ul, 1ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x1ul);
    case 0x1179:
    L_0x1179ul:
      INSN(0x1179ul, "0x1179: JGE 0x118e")
    L_P_0x16:
      INT_EQUAL(unique_space + 0xcf80ul, 1ul, register_space + 0x20bul /* OF */,
                1ul, register_space + 0x207ul /* SF */, 1ul);
      printf("PCODE2C branch cond  %d ", (int)*(unique_space + 0xcf80ul));
      printf("PCODE2C SF  %d ", (int)*(register_space + 0x207ul));
      printf("PCODE2C OF  %d ", (int)*(register_space + 0x20bul));
    L_P_0x17:
      CBRANCH_GOTO_TEMPFIX(ram_space, 0x118eul, 8ul, unique_space, 0xcf80ul,
                           1ul);
    case 0x117b:
    L_0x117bul:
      INSN(0x117bul, "0x117b: MOVSXD RCX,EAX")
    L_P_0x18:
      INT_SEXT(register_space + 0x8ul /* RCX */, 8ul,
               register_space + 0x0ul /* EAX */, 4ul);
    case 0x117e:
    L_0x117eul:
      INSN(0x117eul, "0x117e: MOV R8D,dword ptr [RDX + RCX*0x4]")
    L_P_0x19:
      INT_MULT(unique_space + 0x3300ul, 8ul, register_space + 0x8ul /* RCX */,
               8ul, (uint8_t *)&(long unsigned int){0x4ul}, 0x8ul);
    L_P_0x1a:
      INT_ADD(unique_space + 0x3400ul, 8ul, register_space + 0x10ul /* RDX */,
              8ul, unique_space + 0x3300ul, 8ul);
    L_P_0x1b:
      LOAD(unique_space + 0xbf00ul, 4ul,
           (uint8_t *)&(long unsigned int){0x5942e6dc2ed0ul}, 0x8ul,
           unique_space + 0x3400ul, 8ul);
    L_P_0x1c:
      COPY(register_space + 0x80ul /* R8D */, 4ul, unique_space + 0xbf00ul,
           4ul);
    L_P_0x1d:
      INT_ZEXT(register_space + 0x80ul /* R8 */, 8ul,
               register_space + 0x80ul /* R8D */, 4ul);
    case 0x1182:
    L_0x1182ul:
      INSN(0x1182ul, "0x1182: CMP dword ptr [RSI + RCX*0x4],R8D")
    L_P_0x1e:
      INT_MULT(unique_space + 0x3300ul, 8ul, register_space + 0x8ul /* RCX */,
               8ul, (uint8_t *)&(long unsigned int){0x4ul}, 0x8ul);
    L_P_0x1f:
      INT_ADD(unique_space + 0x3400ul, 8ul, register_space + 0x30ul /* RSI */,
              8ul, unique_space + 0x3300ul, 8ul);
    L_P_0x20:
      LOAD(unique_space + 0xbf00ul, 4ul,
           (uint8_t *)&(long unsigned int){0x5942e6dc2ed0ul}, 0x8ul,
           unique_space + 0x3400ul, 8ul);
    L_P_0x21:
      INT_LESS(register_space + 0x200ul /* CF */, 1ul, unique_space + 0xbf00ul,
               4ul, register_space + 0x80ul /* R8D */, 4ul);
    L_P_0x22:
      LOAD(unique_space + 0xbf00ul, 4ul,
           (uint8_t *)&(long unsigned int){0x5942e6dc2ed0ul}, 0x8ul,
           unique_space + 0x3400ul, 8ul);
    L_P_0x23:
      INT_SBORROW(register_space + 0x20bul /* OF */, 1ul,
                  unique_space + 0xbf00ul, 4ul,
                  register_space + 0x80ul /* R8D */, 4ul);
    L_P_0x24:
      LOAD(unique_space + 0xbf00ul, 4ul,
           (uint8_t *)&(long unsigned int){0x5942e6dc2ed0ul}, 0x8ul,
           unique_space + 0x3400ul, 8ul);
    L_P_0x25:
      INT_SUB(unique_space + 0x29700ul, 4ul, unique_space + 0xbf00ul, 4ul,
              register_space + 0x80ul /* R8D */, 4ul);
    L_P_0x26:
      INT_SLESS(register_space + 0x207ul /* SF */, 1ul,
                unique_space + 0x29700ul, 4ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x4ul);
    L_P_0x27:
      INT_EQUAL(register_space + 0x206ul /* ZF */, 1ul,
                unique_space + 0x29700ul, 4ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x4ul);
    L_P_0x28:
      INT_AND(unique_space + 0x13180ul, 4ul, unique_space + 0x29700ul, 4ul,
              (uint8_t *)&(long unsigned int){0xfful}, 0x4ul);
    L_P_0x29:
      POPCOUNT(unique_space + 0x13200ul, 1ul, unique_space + 0x13180ul, 4ul);
    L_P_0x2a:
      INT_AND(unique_space + 0x13280ul, 1ul, unique_space + 0x13200ul, 1ul,
              (uint8_t *)&(long unsigned int){0x1ul}, 0x1ul);
    L_P_0x2b:
      INT_EQUAL(register_space + 0x202ul /* PF */, 1ul,
                unique_space + 0x13280ul, 1ul,
                (uint8_t *)&(long unsigned int){0x0ul}, 0x1ul);
    case 0x1186:
    L_0x1186ul:
      INSN(0x1186ul, "0x1186: JZ 0x1174")
    L_P_0x2c:
      CBRANCH_GOTO_TEMPFIX(ram_space, 0x1174ul, 8ul, register_space,
                           0x206ul /* ZF */, 1ul);
    case 0x1188:
    L_0x1188ul:
      INSN(0x1188ul, "0x1188: MOV EAX,0x0")
    L_P_0x2d:
      COPY(register_space + 0x0ul /* RAX */, 8ul,
           (uint8_t *)&(long unsigned int){0x0ul}, 0x8ul);
    case 0x118d:
    L_0x118dul:
      INSN(0x118dul, "0x118d: RET ")
    L_P_0x2e:
      LOAD(register_space + 0x288ul /* RIP */, 8ul,
           (uint8_t *)&(long unsigned int){0x5942e6dc2ed0ul}, 0x8ul,
           register_space + 0x20ul /* RSP */, 8ul);
    L_P_0x2f:
      INT_ADD(register_space + 0x20ul /* RSP */, 8ul,
              register_space + 0x20ul /* RSP */, 8ul,
              (uint8_t *)&(long unsigned int){0x8ul}, 0x8ul);
    L_P_0x30:
      RETURN(register_space + 0x288ul /* RIP */, 8ul);
    case 0x118e:
    L_0x118eul:
      INSN(0x118eul, "0x118e: MOV EAX,0x1")
    L_P_0x31:
      COPY(register_space + 0x0ul /* RAX */, 8ul,
           (uint8_t *)&(long unsigned int){0x1ul}, 0x8ul);
    case 0x1193:
    L_0x1193ul:
      INSN(0x1193ul, "0x1193: RET ")
    L_P_0x32:
      LOAD(register_space + 0x288ul /* RIP */, 8ul,
           (uint8_t *)&(long unsigned int){0x5942e6dc2ed0ul}, 0x8ul,
           register_space + 0x20ul /* RSP */, 8ul);
    L_P_0x33:
      INT_ADD(register_space + 0x20ul /* RSP */, 8ul,
              register_space + 0x20ul /* RSP */, 8ul,
              (uint8_t *)&(long unsigned int){0x8ul}, 0x8ul);
    L_P_0x34:
      RETURN(register_space + 0x288ul /* RIP */, 8ul);
    default:
      assert(state->pc != -1); // Unexpected PC value
    }
  }
}
