import argparse
from pypcode import Context, PcodePrettyPrinter


from .printer import *

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="pcode2c", description="Convert pcode to C code"
    )
    parser.add_argument("filename")
    # parser.add_argument("-f", "--function")
    parser.add_argument("--start-address")
    parser.add_argument("--file-offset")
    # parser.add_argument("--")
    parser.add_argument("--size")
    # parser.add_arguments("--disasm-all-bytes")
    # parser.add_argument("--end-address")
    parser.add_argument("--headers", action="store_true", help="Generate arch header")
    # parser.add_argument("--single-file", description="Generate a single file")
    parser.add_argument("-b", "--langid", default="x86:LE:64:default")
    # parser.add_argument("-o", "--output")
    args = parser.parse_args()
    output = []
    if args.headers:
        # with open("arch.h", "w") as f:
        # f.write(f"/* AutoGenerated by pcode.c from {args.filename} */\n")
        # f.writelines(fmt_arch_header(args.langid))
        for line in fmt_arch_header(args.langid):
            print(line)
    # print(pcode2c_header)
    for line in pcode2c(
        args.filename,
        args.langid,
        start_address=int(args.start_address, 16),  # if args.start_address else None,
        file_offset=int(args.file_offset, 16),
        size=int(args.size, 16),
        # end_address=int(args.end_address, 16) if args.end_address else None,
    ):
        print(line)
