from pypcode import Context, PcodePrettyPrinter
import argparse


from .printer import *

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="pcode2c", description="Convert pcode to C code"
    )
    parser.add_argument("filename")
    # parser.add_argument("-f", "--function")
    # parser.add_argument("-a", "--address")
    parser.add_argument("--headers", action="store_true", help="Generate arch header")
    # parser.add_argument("--single-file", description="Generate a single file")
    parser.add_argument("-b", "--langid", default="x86:LE:64:default")
    # parser.add_argument("-o", "--output")
    args = parser.parse_args()
    output = []
    if args.headers:
        # with open("arch.h", "w") as f:
        # f.write(f"/* AutoGenerated by pcode.c from {args.filename} */\n")
        # f.writelines(fmt_arch_header(args.langid))
        for line in fmt_arch_header(args.langid):
            print(line)
    # print(pcode2c_header)
    for line in pcode2c(args.filename, args.langid):
        print(line)
