/* AUTOGENERATED. DO NOT EDIT. */
#include "../../templates/_pcode.h"
void pcode2c(CPUState *state, size_t breakpoint)
{
    uint8_t *register_space = state->reg;
    uint8_t *unique_space = state->unique;
    uint8_t *ram_space = state->ram;
    uint8_t *ram = ram_space; // TODO: remove this
    for (;;)
    {
        switch (state->pc)
        {
        case 0x0:
            INSN(0x0, "0x0: CMP EDI,0x4")
            INT_LESS(register_space + 0x200ull /* CF */, 1ull, register_space + 0x38ull /* EDI */, 4ull, 0x4ull, 0x4ull);
            INT_SBORROW(register_space + 0x20bull /* OF */, 1ull, register_space + 0x38ull /* EDI */, 4ull, 0x4ull, 0x4ull);
            INT_SUB(unique_space + 0x29300ull, 4ull, register_space + 0x38ull /* EDI */, 4ull, 0x4ull, 0x4ull);
            INT_SLESS(register_space + 0x207ull /* SF */, 1ull, unique_space + 0x29300ull, 4ull, 0x0ull, 0x4ull);
            INT_EQUAL(register_space + 0x206ull /* ZF */, 1ull, unique_space + 0x29300ull, 4ull, 0x0ull, 0x4ull);
            INT_AND(unique_space + 0x13180ull, 4ull, unique_space + 0x29300ull, 4ull, 0xffull, 0x4ull);
            POPCOUNT(unique_space + 0x13200ull, 1ull, unique_space + 0x13180ull, 4ull);
            INT_AND(unique_space + 0x13280ull, 1ull, unique_space + 0x13200ull, 1ull, 0x1ull, 0x1ull);
            INT_EQUAL(register_space + 0x202ull /* PF */, 1ull, unique_space + 0x13280ull, 1ull, 0x0ull, 0x1ull);
        case 0x3:
            INSN(0x3, "0x3: JZ 0xb")
            int tmp0;
            if (tmp0 == 0)
            {
                state->pc = 0xb;
                break;
                goto L_b;
            }
            else
            {
                state->pc = 0x5;
                break;
                goto L_5;
            }
            goto L_b;
            CBRANCH(ram_space + 0xbull, 8ull, register_space + 0x206ull /* ZF */, 1ull);
            break;
        case 0x5:
        L_5:
            INSN(0x5, "0x5: MOV EAX,0x1")
            COPY(register_space + 0x0ull /* RAX */, 8ull, 0x1ull, 0x8ull);
        case 0xa:
        L_a:
            INSN(0xa, "0xa: RET ")
            LOAD(register_space + 0x288ull /* RIP */, 8ull, 0x74f310ull, 0x8ull, register_space + 0x20ull /* RSP */, 8ull);
            INT_ADD(register_space + 0x20ull /* RSP */, 8ull, register_space + 0x20ull /* RSP */, 8ull, 0x8ull, 0x8ull);
            RETURN(register_space + 0x288ull /* RIP */, 8ull);
            // break;
            // return;
        case 0xb:
        L_b:
            INSN(0xb, "0xb: PUSH R14")
            COPY(unique_space + 0xed00ull, 8ull, register_space + 0xb0ull /* R14 */, 8ull);
            INT_SUB(register_space + 0x20ull /* RSP */, 8ull, register_space + 0x20ull /* RSP */, 8ull, 0x8ull, 0x8ull);
            STORE(0x74f310ull, 0x8ull, register_space + 0x20ull /* RSP */, 8ull, unique_space + 0xed00ull, 8ull);
        case 0xd:
            INSN(0xd, "0xd: PUSH R13")
            COPY(unique_space + 0xed00ull, 8ull, register_space + 0xa8ull /* R13 */, 8ull);
            INT_SUB(register_space + 0x20ull /* RSP */, 8ull, register_space + 0x20ull /* RSP */, 8ull, 0x8ull, 0x8ull);
            STORE(0x74f310ull, 0x8ull, register_space + 0x20ull /* RSP */, 8ull, unique_space + 0xed00ull, 8ull);
        case 0xf:
            INSN(0xf, "0xf: PUSH R12")
            COPY(unique_space + 0xed00ull, 8ull, register_space + 0xa0ull /* R12 */, 8ull);
            INT_SUB(register_space + 0x20ull /* RSP */, 8ull, register_space + 0x20ull /* RSP */, 8ull, 0x8ull, 0x8ull);
            STORE(0x74f310ull, 0x8ull, register_space + 0x20ull /* RSP */, 8ull, unique_space + 0xed00ull, 8ull);

        default:
            assert(state->pc != -1); // Unexpected PC value
        }
    }
}

// If cprover sees stdlib, it gets radically slower.
#ifndef __CPROVER__
#include <stdlib.h>
#endif

int main()
{

    CPUState state;
    state.reg = malloc(0x2000);
    state.unique = malloc(0x200000);
    state.ram = malloc(0x200000);

    // Initialize state here
    // Uninitialized variables are nondeterministically chosen
    state.pc = 0; /* Initialize function address to */
    ;

    // Run decompiled function
    pcode2c(&state, -1);

    // Check assertions here
    // assert(*(uint64_t*)(state.reg + RAX) == 0xdeadbeef);
    // assert(*(uint64_t*)(state.ram + FOO_ADDR) <= 0xBADDCAFE);
    return 0;
}
